
set UTIL_FLDR_TS to 0.0.
set UTIL_FLDR_TDUR to 300.
set UTIL_FLDR_TDEL to 0.00.

set UTIL_SHSYS_ARM_RLAUNCH_STATUS to true.

set UTIL_SHSYS_ATMOS_ESCAPE_STAGE to 1.
set UTIL_SHSYS_ATMOS_ESCAPE_ALT to 90000.

set UTIL_SHSYS_REENTRY_STAGE to 0.
set UTIL_SHSYS_REENTRY_ALT to 65000.
set UTIL_SHSYS_PARACHUTE_ALT to 1000.

set AP_MODE_FLCS_ENABLED to true.
set AP_MODE_NAV_ENABLED to true.

set AUX_ANTENNAS_NAME to "omni_antenna".
